after_success:
- cd redpen-core/
- mvn clean test -DrepoToken=${REPO_TOKEN} jacoco:report coveralls:jacoco
before_install:
- wget http://www.deflaker.org/maven/apache-maven-3.3.9.zip
- unzip -qq apache-maven-3.3.9.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
before_script:
- sudo apt-get update
- sudo apt-get install phantomjs
language: java

sudo: required

jdk:
  - oraclejdk8
notifications:
  email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
script:
- ./run_test.sh
